package hibernatetestapp;
// Generated 1 Jun, 2018 10:13:49 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Businesssublevels generated by hbm2java
 */
public class Businesssublevels  implements java.io.Serializable {


     private int id;
     private Integer optionid;
     private Integer tableid;
     private Integer businesssubleveloptionid;
     private String code;
     private String name;
     private BigDecimal sortorder;
     private Integer parentbusinessleveloptionid;
     private Character isaloginlevel;
     private Character issystem;
     private Integer levelno;

    public Businesssublevels() {
    }

	
    public Businesssublevels(int id) {
        this.id = id;
    }
    public Businesssublevels(int id, Integer optionid, Integer tableid, Integer businesssubleveloptionid, String code, String name, BigDecimal sortorder, Integer parentbusinessleveloptionid, Character isaloginlevel, Character issystem, Integer levelno) {
       this.id = id;
       this.optionid = optionid;
       this.tableid = tableid;
       this.businesssubleveloptionid = businesssubleveloptionid;
       this.code = code;
       this.name = name;
       this.sortorder = sortorder;
       this.parentbusinessleveloptionid = parentbusinessleveloptionid;
       this.isaloginlevel = isaloginlevel;
       this.issystem = issystem;
       this.levelno = levelno;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getOptionid() {
        return this.optionid;
    }
    
    public void setOptionid(Integer optionid) {
        this.optionid = optionid;
    }
    public Integer getTableid() {
        return this.tableid;
    }
    
    public void setTableid(Integer tableid) {
        this.tableid = tableid;
    }
    public Integer getBusinesssubleveloptionid() {
        return this.businesssubleveloptionid;
    }
    
    public void setBusinesssubleveloptionid(Integer businesssubleveloptionid) {
        this.businesssubleveloptionid = businesssubleveloptionid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(BigDecimal sortorder) {
        this.sortorder = sortorder;
    }
    public Integer getParentbusinessleveloptionid() {
        return this.parentbusinessleveloptionid;
    }
    
    public void setParentbusinessleveloptionid(Integer parentbusinessleveloptionid) {
        this.parentbusinessleveloptionid = parentbusinessleveloptionid;
    }
    public Character getIsaloginlevel() {
        return this.isaloginlevel;
    }
    
    public void setIsaloginlevel(Character isaloginlevel) {
        this.isaloginlevel = isaloginlevel;
    }
    public Character getIssystem() {
        return this.issystem;
    }
    
    public void setIssystem(Character issystem) {
        this.issystem = issystem;
    }
    public Integer getLevelno() {
        return this.levelno;
    }
    
    public void setLevelno(Integer levelno) {
        this.levelno = levelno;
    }




}


