package hibernatetestapp;
// Generated 1 Jun, 2018 10:13:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Optionmst generated by hbm2java
 */
public class Optionmst  implements java.io.Serializable {


     private int id;
     private Integer parentoptionid;
     private Integer companyid;
     private String optiongroupkey;
     private String optioncode;
     private String optionname;
     private String optiondescription;
     private Character optiondisplaytype;
     private String coremodulecode;
     private Integer parentmoduleid;
     private String parentmodulecode;
     private Integer sortorder;
     private String childgroupkey;
     private Character isactive;
     private Character ishidden;
     private Character ismenue;
     private String optionimagethumb;
     private String optionimagelarge;
     private Character requiredchecklist;
     private Character validatedaycloseyn;
     private Character requiredemailprovisionyn;
     private Character allowalerts;
     private Character requiredsmsprovisionyn;
     private Set usermsthistories = new HashSet(0);
     private Set userrolefeaturedefinitions = new HashSet(0);

    public Optionmst() {
    }

	
    public Optionmst(int id) {
        this.id = id;
    }
    public Optionmst(int id, Integer parentoptionid, Integer companyid, String optiongroupkey, String optioncode, String optionname, String optiondescription, Character optiondisplaytype, String coremodulecode, Integer parentmoduleid, String parentmodulecode, Integer sortorder, String childgroupkey, Character isactive, Character ishidden, Character ismenue, String optionimagethumb, String optionimagelarge, Character requiredchecklist, Character validatedaycloseyn, Character requiredemailprovisionyn, Character allowalerts, Character requiredsmsprovisionyn, Set usermsthistories, Set userrolefeaturedefinitions) {
       this.id = id;
       this.parentoptionid = parentoptionid;
       this.companyid = companyid;
       this.optiongroupkey = optiongroupkey;
       this.optioncode = optioncode;
       this.optionname = optionname;
       this.optiondescription = optiondescription;
       this.optiondisplaytype = optiondisplaytype;
       this.coremodulecode = coremodulecode;
       this.parentmoduleid = parentmoduleid;
       this.parentmodulecode = parentmodulecode;
       this.sortorder = sortorder;
       this.childgroupkey = childgroupkey;
       this.isactive = isactive;
       this.ishidden = ishidden;
       this.ismenue = ismenue;
       this.optionimagethumb = optionimagethumb;
       this.optionimagelarge = optionimagelarge;
       this.requiredchecklist = requiredchecklist;
       this.validatedaycloseyn = validatedaycloseyn;
       this.requiredemailprovisionyn = requiredemailprovisionyn;
       this.allowalerts = allowalerts;
       this.requiredsmsprovisionyn = requiredsmsprovisionyn;
       this.usermsthistories = usermsthistories;
       this.userrolefeaturedefinitions = userrolefeaturedefinitions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getParentoptionid() {
        return this.parentoptionid;
    }
    
    public void setParentoptionid(Integer parentoptionid) {
        this.parentoptionid = parentoptionid;
    }
    public Integer getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
    public String getOptiongroupkey() {
        return this.optiongroupkey;
    }
    
    public void setOptiongroupkey(String optiongroupkey) {
        this.optiongroupkey = optiongroupkey;
    }
    public String getOptioncode() {
        return this.optioncode;
    }
    
    public void setOptioncode(String optioncode) {
        this.optioncode = optioncode;
    }
    public String getOptionname() {
        return this.optionname;
    }
    
    public void setOptionname(String optionname) {
        this.optionname = optionname;
    }
    public String getOptiondescription() {
        return this.optiondescription;
    }
    
    public void setOptiondescription(String optiondescription) {
        this.optiondescription = optiondescription;
    }
    public Character getOptiondisplaytype() {
        return this.optiondisplaytype;
    }
    
    public void setOptiondisplaytype(Character optiondisplaytype) {
        this.optiondisplaytype = optiondisplaytype;
    }
    public String getCoremodulecode() {
        return this.coremodulecode;
    }
    
    public void setCoremodulecode(String coremodulecode) {
        this.coremodulecode = coremodulecode;
    }
    public Integer getParentmoduleid() {
        return this.parentmoduleid;
    }
    
    public void setParentmoduleid(Integer parentmoduleid) {
        this.parentmoduleid = parentmoduleid;
    }
    public String getParentmodulecode() {
        return this.parentmodulecode;
    }
    
    public void setParentmodulecode(String parentmodulecode) {
        this.parentmodulecode = parentmodulecode;
    }
    public Integer getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }
    public String getChildgroupkey() {
        return this.childgroupkey;
    }
    
    public void setChildgroupkey(String childgroupkey) {
        this.childgroupkey = childgroupkey;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public Character getIshidden() {
        return this.ishidden;
    }
    
    public void setIshidden(Character ishidden) {
        this.ishidden = ishidden;
    }
    public Character getIsmenue() {
        return this.ismenue;
    }
    
    public void setIsmenue(Character ismenue) {
        this.ismenue = ismenue;
    }
    public String getOptionimagethumb() {
        return this.optionimagethumb;
    }
    
    public void setOptionimagethumb(String optionimagethumb) {
        this.optionimagethumb = optionimagethumb;
    }
    public String getOptionimagelarge() {
        return this.optionimagelarge;
    }
    
    public void setOptionimagelarge(String optionimagelarge) {
        this.optionimagelarge = optionimagelarge;
    }
    public Character getRequiredchecklist() {
        return this.requiredchecklist;
    }
    
    public void setRequiredchecklist(Character requiredchecklist) {
        this.requiredchecklist = requiredchecklist;
    }
    public Character getValidatedaycloseyn() {
        return this.validatedaycloseyn;
    }
    
    public void setValidatedaycloseyn(Character validatedaycloseyn) {
        this.validatedaycloseyn = validatedaycloseyn;
    }
    public Character getRequiredemailprovisionyn() {
        return this.requiredemailprovisionyn;
    }
    
    public void setRequiredemailprovisionyn(Character requiredemailprovisionyn) {
        this.requiredemailprovisionyn = requiredemailprovisionyn;
    }
    public Character getAllowalerts() {
        return this.allowalerts;
    }
    
    public void setAllowalerts(Character allowalerts) {
        this.allowalerts = allowalerts;
    }
    public Character getRequiredsmsprovisionyn() {
        return this.requiredsmsprovisionyn;
    }
    
    public void setRequiredsmsprovisionyn(Character requiredsmsprovisionyn) {
        this.requiredsmsprovisionyn = requiredsmsprovisionyn;
    }
    public Set getUsermsthistories() {
        return this.usermsthistories;
    }
    
    public void setUsermsthistories(Set usermsthistories) {
        this.usermsthistories = usermsthistories;
    }
    public Set getUserrolefeaturedefinitions() {
        return this.userrolefeaturedefinitions;
    }
    
    public void setUserrolefeaturedefinitions(Set userrolefeaturedefinitions) {
        this.userrolefeaturedefinitions = userrolefeaturedefinitions;
    }




}


