package hibernatetestapp;
// Generated 1 Jun, 2018 10:13:49 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userrolefeaturedefinition generated by hbm2java
 */
public class Userrolefeaturedefinition  implements java.io.Serializable {


     private int id;
     private Optionmst optionmst;
     private Tablelist tablelist;
     private Userroles userroles;
     private Character allowaccessyn;
     private Character addrightsyn;
     private Character editrightsyn;
     private Character deleterightsyn;
     private Character viewrightsyn;
     private Character printrightsyn;
     private Integer lastmoduserid;
     private Date lastmoddate;

    public Userrolefeaturedefinition() {
    }

	
    public Userrolefeaturedefinition(int id) {
        this.id = id;
    }
    public Userrolefeaturedefinition(int id, Optionmst optionmst, Tablelist tablelist, Userroles userroles, Character allowaccessyn, Character addrightsyn, Character editrightsyn, Character deleterightsyn, Character viewrightsyn, Character printrightsyn, Integer lastmoduserid, Date lastmoddate) {
       this.id = id;
       this.optionmst = optionmst;
       this.tablelist = tablelist;
       this.userroles = userroles;
       this.allowaccessyn = allowaccessyn;
       this.addrightsyn = addrightsyn;
       this.editrightsyn = editrightsyn;
       this.deleterightsyn = deleterightsyn;
       this.viewrightsyn = viewrightsyn;
       this.printrightsyn = printrightsyn;
       this.lastmoduserid = lastmoduserid;
       this.lastmoddate = lastmoddate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Optionmst getOptionmst() {
        return this.optionmst;
    }
    
    public void setOptionmst(Optionmst optionmst) {
        this.optionmst = optionmst;
    }
    public Tablelist getTablelist() {
        return this.tablelist;
    }
    
    public void setTablelist(Tablelist tablelist) {
        this.tablelist = tablelist;
    }
    public Userroles getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Userroles userroles) {
        this.userroles = userroles;
    }
    public Character getAllowaccessyn() {
        return this.allowaccessyn;
    }
    
    public void setAllowaccessyn(Character allowaccessyn) {
        this.allowaccessyn = allowaccessyn;
    }
    public Character getAddrightsyn() {
        return this.addrightsyn;
    }
    
    public void setAddrightsyn(Character addrightsyn) {
        this.addrightsyn = addrightsyn;
    }
    public Character getEditrightsyn() {
        return this.editrightsyn;
    }
    
    public void setEditrightsyn(Character editrightsyn) {
        this.editrightsyn = editrightsyn;
    }
    public Character getDeleterightsyn() {
        return this.deleterightsyn;
    }
    
    public void setDeleterightsyn(Character deleterightsyn) {
        this.deleterightsyn = deleterightsyn;
    }
    public Character getViewrightsyn() {
        return this.viewrightsyn;
    }
    
    public void setViewrightsyn(Character viewrightsyn) {
        this.viewrightsyn = viewrightsyn;
    }
    public Character getPrintrightsyn() {
        return this.printrightsyn;
    }
    
    public void setPrintrightsyn(Character printrightsyn) {
        this.printrightsyn = printrightsyn;
    }
    public Integer getLastmoduserid() {
        return this.lastmoduserid;
    }
    
    public void setLastmoduserid(Integer lastmoduserid) {
        this.lastmoduserid = lastmoduserid;
    }
    public Date getLastmoddate() {
        return this.lastmoddate;
    }
    
    public void setLastmoddate(Date lastmoddate) {
        this.lastmoddate = lastmoddate;
    }




}


