package hibernatetestapp;
// Generated 1 Jun, 2018 10:13:49 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userroles generated by hbm2java
 */
public class Userroles  implements java.io.Serializable {


     private int id;
     private Tablelist tablelist;
     private String code;
     private String name;
     private Character issystemrole;
     private Character isactive;
     private Integer lastmoduserid;
     private Date lastmoddate;
     private Set userrolefeaturedefinitions = new HashSet(0);

    public Userroles() {
    }

	
    public Userroles(int id) {
        this.id = id;
    }
    public Userroles(int id, Tablelist tablelist, String code, String name, Character issystemrole, Character isactive, Integer lastmoduserid, Date lastmoddate, Set userrolefeaturedefinitions) {
       this.id = id;
       this.tablelist = tablelist;
       this.code = code;
       this.name = name;
       this.issystemrole = issystemrole;
       this.isactive = isactive;
       this.lastmoduserid = lastmoduserid;
       this.lastmoddate = lastmoddate;
       this.userrolefeaturedefinitions = userrolefeaturedefinitions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablelist getTablelist() {
        return this.tablelist;
    }
    
    public void setTablelist(Tablelist tablelist) {
        this.tablelist = tablelist;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Character getIssystemrole() {
        return this.issystemrole;
    }
    
    public void setIssystemrole(Character issystemrole) {
        this.issystemrole = issystemrole;
    }
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }
    public Integer getLastmoduserid() {
        return this.lastmoduserid;
    }
    
    public void setLastmoduserid(Integer lastmoduserid) {
        this.lastmoduserid = lastmoduserid;
    }
    public Date getLastmoddate() {
        return this.lastmoddate;
    }
    
    public void setLastmoddate(Date lastmoddate) {
        this.lastmoddate = lastmoddate;
    }
    public Set getUserrolefeaturedefinitions() {
        return this.userrolefeaturedefinitions;
    }
    
    public void setUserrolefeaturedefinitions(Set userrolefeaturedefinitions) {
        this.userrolefeaturedefinitions = userrolefeaturedefinitions;
    }




}


